### PR TITLE
Updated transaction retry logic

### PR DESCRIPTION
**Pull request by archiesnipes**
Added logic to refetch blockhash and blockheight if blockheighterror is encountered. It might be useful to also add logic to handle other non-blockhash related errors i.e. insufficient funds, as this logic automatically send txn retries 3 times.

Requires some testing by maintainers.

### CODE REVIEW

**Comment by benjiqq** [comment]
many thanks looks great, are we waiting for confirm before each retry? is there a risk of submitting twice eg?

**Comment by lexciobotariu** [comment]
There is a small problem with the latest merge. The bot closes if the 3rd try fails.
I increased the time out to 45s.

```2024-04-08 20:03:39 [info]: Processing pool: CdZMWMUqQT6FnLEhA9x9ipdTjk6rSBg7R4oSBzQa3EDp with 57.00 SOL in liquidity
2024-04-08 20:03:39 [info]: false
2024-04-08 20:03:39 [info]: string
2024-04-08 20:03:39 [info]: TRADE
2024-04-08 20:03:39 [info]: BUY Prepare. Amount: [object Object] Token: BYP3DJ1Xt7y81BAQKNY9h26f3vsJrXUk257WCC6XPCFB
2024-04-08 20:03:40 [info]: Preparing buy. hash 8XUrDyaLG6VmzJmzjTsJsHur9pq5928rm19pSAi8Krcc blockheight 239342000
send transaction attempt: 0
2024-04-08 20:03:40 [info]: Sending buy tx {"mint":"HrUEHnp7GzQQvwuUwGZA9kJXC93dgbk4ovpBNEVBPiGR","signature":"5Y5fY21t6Z92px3YwNq54PN5NHWXjRRJFsRe9HenG38WLGkPMC8Sr2rPHNiGP5onkCHp2q3NiiaqhUCVYngca1tA"}
send transaction attempt: 1
2024-04-08 20:03:40 [info]: Sending buy tx {"mint":"HrUEHnp7GzQQvwuUwGZA9kJXC93dgbk4ovpBNEVBPiGR","signature":"5Y5fY21t6Z92px3YwNq54PN5NHWXjRRJFsRe9HenG38WLGkPMC8Sr2rPHNiGP5onkCHp2q3NiiaqhUCVYngca1tA"}
send transaction attempt: 2
2024-04-08 20:03:40 [info]: Seconds since start: 490
2024-04-08 20:03:40 [info]: Known pools: 1564
2024-04-08 20:03:40 [info]: Total event count: 9334
2024-04-08 20:03:40 [info]: Events per sec: 19
2024-04-08 20:03:40 [info]: Sending buy tx {"mint":"HrUEHnp7GzQQvwuUwGZA9kJXC93dgbk4ovpBNEVBPiGR","signature":"5Y5fY21t6Z92px3YwNq54PN5NHWXjRRJFsRe9HenG38WLGkPMC8Sr2rPHNiGP5onkCHp2q3NiiaqhUCVYngca1tA"}
2024-04-08 20:03:50 [info]: Seconds since start: 500
2024-04-08 20:03:50 [info]: Known pools: 1585
2024-04-08 20:03:50 [info]: Total event count: 9561
2024-04-08 20:03:50 [info]: Events per sec: 19
2024-04-08 20:04:00 [info]: Seconds since start: 510
2024-04-08 20:04:00 [info]: Known pools: 1606
2024-04-08 20:04:00 [info]: Total event count: 9804
2024-04-08 20:04:00 [info]: Events per sec: 19
2024-04-08 20:04:10 [info]: Seconds since start: 520
2024-04-08 20:04:10 [info]: Known pools: 1625
2024-04-08 20:04:10 [info]: Total event count: 9959
2024-04-08 20:04:10 [info]: Events per sec: 19
2024-04-08 20:04:20 [info]: Seconds since start: 530
2024-04-08 20:04:20 [info]: Known pools: 1650
2024-04-08 20:04:20 [info]: Total event count: 10196
2024-04-08 20:04:20 [info]: Events per sec: 19
2024-04-08 20:04:25 [error]: Failed to confirm transaction:
Error: failed to confirm transaction, Transaction confirmation timed out
    at /root/sniperbot/src/transact.ts:164:23
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.```

**Comment by benjiqq** [comment]
many thanks @lexciobotariu , i'll revert the commit and merge this to develop and that branch can be used for testing first

**Comment by archiesnipes** [comment]
> many thanks @lexciobotariu , i'll revert the commit and merge this to develop and that branch can be used for testing first



> There is a small problem with the latest merge. The bot closes if the 3rd try fails. I increased the time out to 45s.
> 
> ```
> 2024-04-08 20:03:39 [info]: false
> 2024-04-08 20:03:39 [info]: string
> 2024-04-08 20:03:39 [info]: TRADE
> 2024-04-08 20:03:39 [info]: BUY Prepare. Amount: [object Object] Token: BYP3DJ1Xt7y81BAQKNY9h26f3vsJrXUk257WCC6XPCFB
> 2024-04-08 20:03:40 [info]: Preparing buy. hash 8XUrDyaLG6VmzJmzjTsJsHur9pq5928rm19pSAi8Krcc blockheight 239342000
> send transaction attempt: 0
> 2024-04-08 20:03:40 [info]: Sending buy tx {"mint":"HrUEHnp7GzQQvwuUwGZA9kJXC93dgbk4ovpBNEVBPiGR","signature":"5Y5fY21t6Z92px3YwNq54PN5NHWXjRRJFsRe9HenG38WLGkPMC8Sr2rPHNiGP5onkCHp2q3NiiaqhUCVYngca1tA"}
> send transaction attempt: 1
> 2024-04-08 20:03:40 [info]: Sending buy tx {"mint":"HrUEHnp7GzQQvwuUwGZA9kJXC93dgbk4ovpBNEVBPiGR","signature":"5Y5fY21t6Z92px3YwNq54PN5NHWXjRRJFsRe9HenG38WLGkPMC8Sr2rPHNiGP5onkCHp2q3NiiaqhUCVYngca1tA"}
> send transaction attempt: 2
> 2024-04-08 20:03:40 [info]: Seconds since start: 490
> 2024-04-08 20:03:40 [info]: Known pools: 1564
> 2024-04-08 20:03:40 [info]: Total event count: 9334
> 2024-04-08 20:03:40 [info]: Events per sec: 19
> 2024-04-08 20:03:40 [info]: Sending buy tx {"mint":"HrUEHnp7GzQQvwuUwGZA9kJXC93dgbk4ovpBNEVBPiGR","signature":"5Y5fY21t6Z92px3YwNq54PN5NHWXjRRJFsRe9HenG38WLGkPMC8Sr2rPHNiGP5onkCHp2q3NiiaqhUCVYngca1tA"}
> 2024-04-08 20:03:50 [info]: Seconds since start: 500
> 2024-04-08 20:03:50 [info]: Known pools: 1585
> 2024-04-08 20:03:50 [info]: Total event count: 9561
> 2024-04-08 20:03:50 [info]: Events per sec: 19
> 2024-04-08 20:04:00 [info]: Seconds since start: 510
> 2024-04-08 20:04:00 [info]: Known pools: 1606
> 2024-04-08 20:04:00 [info]: Total event count: 9804
> 2024-04-08 20:04:00 [info]: Events per sec: 19
> 2024-04-08 20:04:10 [info]: Seconds since start: 520
> 2024-04-08 20:04:10 [info]: Known pools: 1625
> 2024-04-08 20:04:10 [info]: Total event count: 9959
> 2024-04-08 20:04:10 [info]: Events per sec: 19
> 2024-04-08 20:04:20 [info]: Seconds since start: 530
> 2024-04-08 20:04:20 [info]: Known pools: 1650
> 2024-04-08 20:04:20 [info]: Total event count: 10196
> 2024-04-08 20:04:20 [info]: Events per sec: 19
> 2024-04-08 20:04:25 [error]: Failed to confirm transaction:
> Error: failed to confirm transaction, Transaction confirmation timed out
>     at /root/sniperbot/src/transact.ts:164:23
> error Command failed with exit code 1.
> info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.```
> ```
good catch.

**Pull request merged**
